language: php

php:
  - '5.6'

branches:
 only:
 - master

before_install:
 - composer self-update

before_script:
 - composer install

script: phpunit --configuration phpunit.xml

deploy:
  provider: heroku
  api_key: $API_KEY
  app: farming-manager
  on: master
