language: php

php:
  - '5.6'

before_install:
 - composer self-update

before_script:
 - composer install
 - composer dumpautoload -o

script: phpunit --configuration tests/phpunit.xml --coverage-text

notifications:
  email: false

after_success:
 "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://vweb06.nitrado.net/"
