language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer install --prefer-source --no-interaction
  - vendor/bin/install-phalcon.sh

before_script:
 - composer install

script: phpunit --configuration tests/phpunit.xml --coverage-text

notifications:
  email: false

deploy:
  provider: heroku
  api_key: $API_KEY
  app: farming-manager
