language: php

php:
  - '5.6'

before_install:
 - composer self-update

before_script:
 - composer install
 - composer dumpautoload -o

script: phpunit --configuration tests/phpunit.xml --coverage-text

notifications:
  email: false
