language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'

before_install:
 - composer self-update

before_script:
 - composer install
 - composer dumpautoload -o

script: phpunit --configuration tests/phpunit.xml --coverage-text

notifications:
  email: false

deploy:
  provider: heroku
  api_key: $API_KEY
  app: farming-manager
